version: '20.10.17'
services:
  postgres:
    image: postgres:14
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestion_proyecto_db_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: